tap "FelixKratz/formulae"
tap "nikitabobko/tap"

brew "stow"
brew "git"
brew "zsh"
brew "tmux"
brew "fish"
brew "yazi"
brew "clippy"
brew "mpv"
brew "ffmpeg"
brew "media-info"
brew "borders"
brew "sketchybar"
brew "starship"
brew "neovim"
brew "tree-sitter-cli"
brew "imagemagick"
brew "ghostscript"
brew "pngpaste"

cask "ghostty"
cask "font-sketchybar-app-font"
cask "alacritty"
cask "karabiner-elements"
cask "nikitabobko/tap/aerospace"