tap "FelixKratz/formulae"
tap "nikitabobko/tap"
tap "anomalyco/tap"

brew "stow"
brew "git"
brew "zsh"
brew "tmux"
brew "fish"
brew "yazi"
brew "clippy"
brew "mpv"
brew "ffmpeg"
brew "media-info"
brew "borders"
brew "sketchybar"
brew "starship"
brew "neovim"
brew "tree-sitter-cli"
brew "uv"
brew "imagemagick"
brew "ghostscript"
brew "pngpaste"

# cli utilities
brew "neofetch"
brew "cmatrix"
brew "btop"
brew "dooit"
brew "anomalyco/tap/opencode"

cask "ghostty"
cask "font-sketchybar-app-font"
cask "alacritty"
cask "karabiner-elements"
cask "nikitabobko/tap/aerospace"