" ========================================
" basic config
" ========================================

" set line number
set number
" set relative line number
set relativenumber

" set syntax heighlight
syntax on

" set auto indent
set autoindent
set smartindent

" set indent space
set tabstop=4
set shiftwidth=4
set expandtab

" heighlight current line
" set cursorline

" set term color
" set termguicolors

" set laststatus
set laststatus=1
set ruler 

set nobackup
set noswapfile



