#!/bin/bash

options=(
    style=round
    width=12.0
    hidpi=on

    # active_color='gradient(top_left=0xff89b4fa,bottom_right=0xffcba6f7)'
    # inactive_color='glow(0xff585b70)'

    active_color='glow(0xff89b4fa)'
    inactive_color=0xff6c7086
)

borders "${options[@]}"
