local pack_opts = { load = true, confirm = false }

vim.pack.add({ "https://github.com/folke/which-key.nvim" }, pack_opts)

require("which-key").setup({
  icons = {
    group = "",
    separator = "-",
    rules = false,
  },
  spec = {
    { "<leader>f", group = "Find" },
    { "<leader>l", group = "LSP" },
    { "<leader>d", group = "Debug" },
    { "<leader>r", group = "Run" },
    { "<leader>b", group = "Buffers" },
    { "<leader>m", group = "Markdown" },
    { "<leader>mm", desc = "Toggle markdown render" },
    { "<leader>mp", desc = "Paste image" },
    { "<leader>mh", desc = "Preview image/formula" },
    { "<leader>mb", desc = "Backlinks" },
    { "<leader>mc", desc = "Toggle checkbox" },
    { "<leader>ml", desc = "Follow wiki link" },
    { "<leader>e", desc = "Toggle file tree" },
    { "<leader>o", desc = "Focus file tree" },
    { "<leader>lS", desc = "Symbols outline (aerial)" },
    { "<leader>lf", desc = "Format buffer" },
    { "<leader>li", desc = "Toggle inlay hints" },
    { "<leader>lr", desc = "Rename symbol" },
    { "<leader>la", desc = "Code action" },
    { "<leader>ld", desc = "Line diagnostic" },
    { "<leader>rr", desc = "Run task template" },
    { "<leader>ru", desc = "uv sync" },
    { "<leader>ro", desc = "Toggle task list" },
    { "<leader>ra", desc = "Overseer quick action" },
    { "<leader>ds", desc = "Start/Continue debug" },
    { "<leader>du", desc = "Toggle debug UI" },
    { "<leader>db", desc = "Toggle breakpoint" },
    { "<leader>w", desc = "Save buffer" },
    { "<leader>q", desc = "Quit window" },
    { "<leader>Q", desc = "Quit all" },
    { "<leader>|", desc = "Split vertically" },
    { "<leader>\\", desc = "Split horizontally" },
    { "]", group = "Next" },
    { "[", group = "Previous" },
  },
})
